#python train.py --name SPADE_StripPooling_cat_twolayer_ppooling --dataset_mode cityscapes --dataroot /data/engs-tvg/engs1870/SPADE/datasets/Cityscapes/data --niter 100 --niter_decay 100 --gpu_ids 0 --checkpoints_dir /data/engs-tvg/engs1870/checkpoints --batchSize 8 --save_epoch_freq 5  --save_latest_freq 1000 
#--continue_train;

#python train.py --name SPADE_StripPooling_cat_twolayer_ppooling4 --dataset_mode cityscapes --dataroot /data/engs-tvg/engs1993/SPADE/datasets/Cityscapes/data --niter 100 --niter_decay 100 --gpu_ids 0 --checkpoints_dir /data/engs-tvg/engs1993/checkpoints --batchSize 4 --save_epoch_freq 5  --save_latest_freq 1000 --continue_train;

#python train.py --name SPADE_StripPooling_cat_twolayer_ppooling4_ade --dataset_mode ade20k --dataroot /data/engs-tvg/engs1993/SPADE/datasets/ADEChallengeData2016 --niter 100 --niter_decay 100 --gpu_ids 0,1,2,3 --checkpoints_dir /data/engs-tvg/engs1993/checkpoints --batchSize 16 --save_epoch_freq 5  --save_latest_freq 1000 
#--continue_train;

#python train.py --name SPADE_StripPooling_cat_twolayer_ppooling4_celeba512 --dataset_mode celeba --label_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/labels/train_label --label_nc 19 --no_instance --image_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/images/train_img  --niter 50 --niter_decay 50 --gpu_ids 0,1,2,3 --checkpoints_dir /data/engs-tvg/engs1993/checkpoints  --batchSize 8 --save_epoch_freq 5  --save_latest_freq 1000 --continue_train;

#python test.py --name SPADE_StripPooling_cat_twolayer_ppooling4_celeba512 --dataset_mode celeba --label_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/labels/test_label --label_nc 19 --no_instance --image_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/images/test_img --gpu_ids 0 --results_dir /data/engs-tvg/engs1993/SPADE_results --checkpoints_dir /data/engs-tvg/engs1993/checkpoints --batchSize 1 --which_epoch 100;

python test.py --name SPADE_StripPooling_cat_twolayer_ppooling4_celeba512 --dataset_mode celeba --label_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/labels/test_label --label_nc 19 --no_instance --image_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/images/test_img --gpu_ids 0 --results_dir /data/engs-tvg/engs1993/SPADE_results --checkpoints_dir /data/engs-tvg/engs1993/checkpoints --batchSize 1 --which_epoch 95;
python test.py --name SPADE_StripPooling_cat_twolayer_ppooling4_celeba512 --dataset_mode celeba --label_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/labels/test_label --label_nc 19 --no_instance --image_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/images/test_img --gpu_ids 0 --results_dir /data/engs-tvg/engs1993/SPADE_results --checkpoints_dir /data/engs-tvg/engs1993/checkpoints --batchSize 1 --which_epoch 90;
python test.py --name SPADE_StripPooling_cat_twolayer_ppooling4_celeba512 --dataset_mode celeba --label_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/labels/test_label --label_nc 19 --no_instance --image_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/images/test_img --gpu_ids 0 --results_dir /data/engs-tvg/engs1993/SPADE_results --checkpoints_dir /data/engs-tvg/engs1993/checkpoints --batchSize 1 --which_epoch 85;
python test.py --name SPADE_StripPooling_cat_twolayer_ppooling4_celeba512 --dataset_mode celeba --label_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/labels/test_label --label_nc 19 --no_instance --image_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/images/test_img --gpu_ids 0 --results_dir /data/engs-tvg/engs1993/SPADE_results --checkpoints_dir /data/engs-tvg/engs1993/checkpoints --batchSize 1 --which_epoch 80;
python test.py --name SPADE_StripPooling_cat_twolayer_ppooling4_celeba512 --dataset_mode celeba --label_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/labels/test_label --label_nc 19 --no_instance --image_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/images/test_img --gpu_ids 0 --results_dir /data/engs-tvg/engs1993/SPADE_results --checkpoints_dir /data/engs-tvg/engs1993/checkpoints --batchSize 1 --which_epoch 75;
python test.py --name SPADE_StripPooling_cat_twolayer_ppooling4_celeba512 --dataset_mode celeba --label_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/labels/test_label --label_nc 19 --no_instance --image_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/images/test_img --gpu_ids 0 --results_dir /data/engs-tvg/engs1993/SPADE_results --checkpoints_dir /data/engs-tvg/engs1993/checkpoints --batchSize 1 --which_epoch 70;
python test.py --name SPADE_StripPooling_cat_twolayer_ppooling4_celeba512 --dataset_mode celeba --label_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/labels/test_label --label_nc 19 --no_instance --image_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/images/test_img --gpu_ids 0 --results_dir /data/engs-tvg/engs1993/SPADE_results --checkpoints_dir /data/engs-tvg/engs1993/checkpoints --batchSize 1 --which_epoch 65;
python test.py --name SPADE_StripPooling_cat_twolayer_ppooling4_celeba512 --dataset_mode celeba --label_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/labels/test_label --label_nc 19 --no_instance --image_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/images/test_img --gpu_ids 0 --results_dir /data/engs-tvg/engs1993/SPADE_results --checkpoints_dir /data/engs-tvg/engs1993/checkpoints --batchSize 1 --which_epoch 60;
python test.py --name SPADE_StripPooling_cat_twolayer_ppooling4_celeba512 --dataset_mode celeba --label_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/labels/test_label --label_nc 19 --no_instance --image_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/images/test_img --gpu_ids 0 --results_dir /data/engs-tvg/engs1993/SPADE_results --checkpoints_dir /data/engs-tvg/engs1993/checkpoints --batchSize 1 --which_epoch 55;
python test.py --name SPADE_StripPooling_cat_twolayer_ppooling4_celeba512 --dataset_mode celeba --label_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/labels/test_label --label_nc 19 --no_instance --image_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/images/test_img --gpu_ids 0 --results_dir /data/engs-tvg/engs1993/SPADE_results --checkpoints_dir /data/engs-tvg/engs1993/checkpoints --batchSize 1 --which_epoch 50;
python test.py --name SPADE_StripPooling_cat_twolayer_ppooling4_celeba512 --dataset_mode celeba --label_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/labels/test_label --label_nc 19 --no_instance --image_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/images/test_img --gpu_ids 0 --results_dir /data/engs-tvg/engs1993/SPADE_results --checkpoints_dir /data/engs-tvg/engs1993/checkpoints --batchSize 1 --which_epoch 45;
python test.py --name SPADE_StripPooling_cat_twolayer_ppooling4_celeba512 --dataset_mode celeba --label_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/labels/test_label --label_nc 19 --no_instance --image_dir /data/engs-tvg/engs1993/SPADE/datasets/celeba/images/test_img --gpu_ids 0 --results_dir /data/engs-tvg/engs1993/SPADE_results --checkpoints_dir /data/engs-tvg/engs1993/checkpoints --batchSize 1 --which_epoch 40;
